### Delete Webhook
DELETE {{api_base_url}}/configs/v1/webhooks/{{webhook_id}}
Content-Type: application/json
Authorization: O-Bearer {{access_token}}

### Postman test script reference
# pm.test('Delete webhook success', function () {
#   pm.expect(pm.response.code).to.be.oneOf([200, 204]);
# });
